# MLops pipeline for wine model


# trigger:
# - main

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7

- script: |
    pip install pytest requests setuptools wheel
    pip install -U databricks-cli
  displayName: 'Load Python Dependencies'

- script: |
    echo "
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN)" | dbfs configure --token
  displayName: 'Configure dbfs cli'

- script: |
    dbfs ls
  displayName: 'test dbfs cli'


- checkout: self
  persistCredentials: true
  clean: true

- script: git checkout dev
  displayName: 'Get Latest Branch'

- script: |
    databricks workspace mkdirs /dltp8tdylp/deploy
    databricks workspace import -l PYTHON -o $(Build.SourcesDirectory)/"notebooks/dltp8tdylp/deploy_azure_ml_model_.py" "/dltp8tdylp/deploy/deploy_azure_ml_model"
  displayName: 'Import ML Deploy Notebook'

# - task: PythonScript@0
#   inputs:
#     scriptSource: 'filePath'
#     scriptPath: '$(Build.Repository.LocalPath)/scripts/executenotebook.py'
#     arguments: '--shard $(DATABRICKS_HOST) --token $(DATABRICKS_TOKEN) --cluster $(EXISTING_CLUSTER_ID) --localpath $(Build.Repository.LocalPath)/notebooks/Users/christopher.chalcraft@databricks.com/mlops-demo/deploy/ --workspacepath /Users/christopher.chalcraft@databricks.com/mlops-demo/deploy/ --outfilepath /home/vsts/work/1/s/notebooks/Users/christopher.chalcraft@databricks.com --params model_name=$(model_name)'
#   displayName: 'Deploy mlFlow Model from Registry to Azure ML for Testing'

# - script: |
#     echo $(response)
#   displayName: 'API URL'
# - script: |
#     databricks workspace import "$(Build.Repository.LocalPath)/notebooks/Users/christopher.chalcraft@databricks.com/mlops-demo/test/test_api.py" "/Users/christopher.chalcraft@databricks.com/ML/test/test_api.py"  --language PYTHON -o
#   displayName: 'Import ML Test Notebook'
# - task: PythonScript@0
#   inputs:
#     scriptSource: 'filePath'
#     scriptPath: '$(Build.Repository.LocalPath)/scripts/executenotebook.py'
#     arguments: '--shard $(DATABRICKS_HOST) --token $(DATABRICKS_TOKEN) --cluster $(EXISTING_CLUSTER_ID) --localpath $(Build.Repository.LocalPath)/notebooks/Users/christopher.chalcraft@databricks.com/ML/test/ --workspacepath /Users/christopher.chalcraft@databricks.com/mlops-demo/test/ --outfilepath /home/vsts/work/1/s/notebooks/Users/christopher.chalcraft@databricks.com --params model_name=$(model_name),scoring_uri=$(response)'
#   displayName: 'Test mlFlow Model from Registry against REST API' 

#- task: PythonScript@0
#  inputs:
#    scriptSource: 'filePath'
#    scriptPath: '$(Build.Repository.LocalPath)/scripts/mlflow.py'
#    arguments: ''
#  displayName: 'Promote mlFlow Registry model to Production' 

#- script: |
#    echo $(response)
#  displayName: 'Model Production Version'
